services:
  ms-kafka-aggregator:
    image: 717279720802.dkr.ecr.ap-southeast-1.amazonaws.com/pixelsofts/ms-kafka-aggregator:latest
    container_name: ms-kafka-aggregator
    env_file:
      - .env
    volumes:
      - ./certs:/certs:ro
    restart: unless-stopped